labels:
  - name: complete
    labeled:
      issue:
        body: This issue has been marked as complete as it is believed the original issue has been fixed/answered or cannot be actioned. The issue will be closed in three days. If you feel the issue requires further attention then please let me know. Thanks!
